name: Release & Provenance
on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build artifacts
        run: |
          tar -czvf openssf-criticality-suite.tar.gz .
      - name: Generate hashes
        id: hash
        run: |
          echo "hashes=$(sha256sum openssf-criticality-suite.tar.gz | base64 -w0)" >> "$GITHUB_OUTPUT"

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.9.0
    with:
      base64-subjects: "${{ needs.build.outputs.hashes }}"
      upload-assets: true
